@startuml buom arch design

component buom
component consoleBot

component restBots {
  component slackBot
  component skypeBot
}

[config]

package "processors" as po {
  component MessageProcessor as processor
  component matchers {
    component helloMatcher
    component witaiMatcher
  }

  component handler {
    () GoogleSearchHandler
    package "printers" as p {
      component printer
      database mongo
      database constant
    }
    note top of printers: print answers (from json/database)
  }
}

buom -> config: use
buom --> consoleBot: use
buom --> restBots: use

processor --> witaiMatcher
processor --> helloMatcher

processor --> handler: process intent

handler --> printer
GoogleSearchHandler -> printer

printers --> constant
printers --> mongo

consoleBot --> processor: startWith
restBots --> processor: startWith

note bottom of skypeBot: Microsoft Botbuilder Framework
note top of buom: based bottender framework
@enduml
