@startuml buom arch design

component buom
component consoleBot

component restBots {
  component slackBot
  component skypeBot
}

[config]

package "processors" as po {
  component MessageProcessor as processor
  component matchers {
    component helloMatcher
    component witaiMatcher
  }

  component handlers {
    component GoogleSearchHandler
    component defaultHandler
    package "printers" as p {
      component printer
      database mongo
      database constant
    }
    note top of printers: print answers (from json/database)
  }
}

buom -> config: use
buom --> consoleBot: use
buom --> restBots: use

processor --> witaiMatcher: match
processor --> helloMatcher: match

processor --> handlers: process

defaultHandler --> printers: use
GoogleSearchHandler -> printers: use

printers --> constant: is
printers --> mongo: is

consoleBot --> processor: startWith
restBots --> processor: startWith

note bottom of skypeBot: Microsoft Botbuilder Framework
note top of buom: based bottender framework
@enduml
