@startuml buom arch design
component buom {
  component consoleBot
  component restBots {
    [slackBot]
    [skypeBot]
  }
}

component handler {
}

consoleBot - restBots: or

buom --> handler: use

note bottom of skypeBot: Microsoft Botbuilder Framework
note top of buom: based bottender framework
@enduml
