@startuml matcher
start

:i=0;

while (i < matchers.length?) is (yes)
  :take matcher at #i;
  :intent = matcher.match;

  if (have intent?) then (yes)
    :printer print context and intent;
    stop
  else (no)
    :increase i;
  endif
endwhile (no)

if (i == matchers.length?) then (yes)
  :printer print context and unknown intent;
else (no)
endif

stop

@enduml
